title: Maria Camila Gómez 
description: Blog
author: Maria Camila Gómez
logo: /static/img/camila.jpg
github: https://github.com/camigomez35
about: Estudiante de Ingeniería de Sistemas

baseurl: ""
url: "https://codeasashu.github.io/hcz-jekyll-blog"

disqus_shortname: camigomez35
google_analytics: UA-72862926-1

share:
  twitter_username: \camigomez318
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
